### ISSUE TITLE
Installing the git package fails

### ISSUE THREAD

**Issue by ErikWahlstrom** [GuOrg/Gu.Persist#34]
Had to install libgit2sharp before installing the package.

**Comment by JohanLarsson** [comment]
```xml
<PackageReference Include="LibGit2Sharp" Version="0.26.2" PrivateAssets="none"/>
```

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

Default is excluding`content;analyzers;build` for transitive.
